language: php

dist: trusty

matrix:
  include:
    - php: 5.5
      env: SYMFONY_VERSION='^3.3'
    - php: 7.0
      env: SYMFONY_VERSION='^3.3'
    - php: 7.0
      env: SYMFONY_VERSION='^3.4'
    - php: 7.1
      env: SYMFONY_VERSION='^3.3'
    - php: 7.1
      env: SYMFONY_VERSION='^3.4'
    - php: 7.1.3
      env: SYMFONY_VERSION='^3.4'
    - php: 7.1.3
      env: SYMFONY_VERSION='^4.0'
    - php: 7.2
      env: SYMFONY_VERSION='^3.4'
    - php: 7.2
      env: SYMFONY_VERSION='^4.0'

  fast_finish: true

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;
  - composer update

script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --diff
  - ./vendor/bin/phpunit
