#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\ErrorHandler\Debug;

set_time_limit(0);
require __DIR__.'/../vendor/autoload.php';

$dotenv = new Dotenv(false);
$dotenv->bootEnv(__DIR__.'/.env', 'test');

// This makes the GOOGLE_APPLICATION_CREDENTIALS an absolute path
if (isset($_ENV['GOOGLE_APPLICATION_CREDENTIALS']) && 0 !== strpos($_ENV['GOOGLE_APPLICATION_CREDENTIALS'], '/')) {
    $_ENV['GOOGLE_APPLICATION_CREDENTIALS'] = $_SERVER['GOOGLE_APPLICATION_CREDENTIALS'] = dirname(__DIR__).'/'.$_ENV['GOOGLE_APPLICATION_CREDENTIALS'];
}
putenv("GOOGLE_APPLICATION_CREDENTIALS={$_ENV['GOOGLE_APPLICATION_CREDENTIALS']}");
putenv("GOOGLE_CLOUD_PROJECT={$_ENV['GOOGLE_CLOUD_PROJECT']}");

$input = new ArgvInput();
Debug::enable();
$kernel = new TestKernel('test', true);
$application = new Application($kernel);
$application->run($input);
