#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;
use Symfony\Component\Dotenv\Dotenv;

set_time_limit(0);
require __DIR__.'/../vendor/autoload.php';

$dotenv = new Dotenv();
$dotenv->loadEnv(__DIR__.'/.env', 'APP_ENV', 'test');

$input = new ArgvInput();
Debug::enable();
$kernel = new TestKernel('test', true);
$application = new Application($kernel);
$application->run($input);
